name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - name: Update sponsors
        run: bun run update-degen-sponsors
        env:
          PAT: ${{ secrets.PAT }}
          FARCASTER_USERNAME: ${{ secrets.FARCASTER_USERNAME }}
          NEYNAR_API_KEY: ${{ secrets.NEYNAR_API_KEY }}
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}

      - name: Commit changes
        run: bash ./commit.sh

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: "README.md"

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: "."
